apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: zad17xlf3-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/zad17xlf3-java-springboot-gitops